version: "3"
services:
  ansible:
    image: avdteam/base:3.6
    volumes:
      - ../:/projects
    command: [ "/bin/sh", "-c", "while true; do sleep 30; done;" ]

  webdoc_cvp:
    image: titom73/mkdocs:latest
    volumes:
      - ../ansible-cvp:/docs
    ports:
      - 8001:8000
    entrypoint: ""
    command: ["sh", "-c", "pip install -r ansible_collections/arista/cvp/docs/requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000 -f mkdocs.yml"]

  webdoc_avd:
    image: titom73/mkdocs:latest
    volumes:
      - ../ansible-avd:/docs
    ports:
      - 8000:8000
    entrypoint: ""
    command: ["sh", "-c", "pip install -r ansible_collections/arista/avd/docs/requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000 -f mkdocs.yml"]